# Generated by Django 2.0.1 on 2018-02-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_auto_20180225_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equiponinja',
            name='numero_equipo',
        ),
        migrations.AddField(
            model_name='equiponinja',
            name='nombre_equipo',
            field=models.CharField(default='Nombre de Equipo', max_length=30),
        ),
    ]
