# Generated by Django 2.0.1 on 2018-03-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0007_auto_20180302_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='user_last',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='perfil',
            name='user_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
