# Generated by Django 2.0.1 on 2018-04-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0010_productos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='id_producto',
            new_name='id',
        ),
    ]
