# Generated by Django 2.0.1 on 2018-04-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0011_auto_20180420_1923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Products',
        ),
    ]
