# Generated by Django 2.0.1 on 2018-04-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0012_auto_20180420_1925'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
