# Generated by Django 2.0.1 on 2018-04-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0013_auto_20180423_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
